- source/apollo-client/customization.md
- source/apollo-client/index.md
> Update redux integration docs

- source/apollo-client/index.md
> Update networkInterface example

- source/apollo-client/react.md
> Update react docs

- source/apollo-client/angular2.md
`angular2-apollo` has now `@Apollo` decorator
https://github.com/apollostack/angular2-apollo/pull/8
> Update Angular2 with Apollo decorator

- source/apollo-server/guide.md
Small typo - updated to refer to blog app. Thanks!
> No todos here! (switched "todos" to "blog")

- source/apollo-client/react.md
@jbaxleyiii Added refetch() new syntax to doc
> Document refetch() with variables support

- source/apollo-client/angular2.md
Those "Edit on GitHub" links are really cool :)
> Typo fix :)

- source/apollo-client/index.md
> Include docs on store rehydration via initial state

- source/apollo-client/core.md
Addresses https://github.com/apollostack/apollo-client/issues/130.
Hope it pleases.
> Document fetch polyfill

- source/apollo-client/angular2.md
It will be more unified with the rest of docs.
Side menu will look like this:
- Bootstrap
- Angular2Apollo service (contains: Queries, Mutations)
- Apollo decorator (contains: Queries, Mutations)
- ApolloQueryPipe
- Development
instead of 
- Install
- Bootstrap
- Inject Angular2Apollo
- Bind to query
- ApolloQueryPipe
- Mutations
- Development
@Urigo
> Angular2: Describe service, decorator and examples

- source/apollo-client/react.md
Corresponding PR (https://github.com/apollostack/react-apollo/pull/31) and issue (https://github.com/apollostack/react-apollo/issues/30)
> update react-apollo api for changes to returned prop

- source/index.md
This PR takes the example project I built and adds it to the list of examples in the docs.
@helfer
> Add additional example to Docs

- source/apollo-client/core.md
See https://github.com/apollostack/apollo-client/pull/153 for client PR
> add in information about the option to poll a query

- source/apollo-client/react.md
> Fix #watchQuery and #mutate links.

- source/apollo-server/tools.md
> tools.md: Formatting and clarity

- source/apollo-client/angular2.md
> Update Angular2 to use new API

- source/apollo-server/scalars.md
The proposal for the scalars documentation.
> Added scalars

- source/apollo-client/react.md
As added in https://github.com/apollostack/react-apollo/commit/27be0a38640009cf95a9644cc71b486ab32464e7
> Add `watchQuery` to docs for `react-apollo`.

- source/apollo-client/react.md
Addresses #16 
Just included the bare essentials to use React Router. Can go into more detail if necessary but there isn't much to say that isn't already covered in the React Router documentation.
> Documentation on using React Router

- source/apollo-client/angular2.md
https://github.com/apollostack/angular2-apollo/blob/master/CHANGELOG.md#v041
> Add angular2Apollo.query() and ApolloQueryObservable

- source/apollo-client/index.md
Hey!
This pull request adds some information regarding `afterwares` which was introduced with this [PR](https://github.com/apollostack/apollo-client/pull/399).
> Add documentation regarding afterwares

- source/apollo-client/react.md
I believe these were wrong, but please double-check before merging @jbaxleyiii
> Fix broken examples

- package.json
- source/apollo-client/react.md
http://docs.apollostack.com/vreact-apollo-0.4.0/apollo-client/react.html
Still to resolve:
> Version react apollo 0.4.0

- source/apollo-client/index.md
Fix argument for applyAfterware function:
Corresponding https://github.com/apollostack/apollo-client/blob/v0.4.13/src/networkInterface.ts#L149
> Fix argument for applyAfterware function call

- source/meteor.md
The url was pointing to the graphql endpoint, not the GraphiQL ide
> Change graphiql url

- source/index.md
Outline hot code reload feature for backend and frontend of apollo-fullstack-starter-kit
> Outline important hot code reload feature

- _config.yml
- source/apollo-client-api.md
- source/how-it-works.md
- source/index.md
- source/network.md
@stubailo I did a pass on the core docs. I think it makes more sense after this, certainly to me it does. I don't know whether there's anything missing though.
One thing I came across is I think the explanations in Devtools/Queries+Mutations+Lifecycle are pretty confusing and I don't think they're that helpful. I.e if you're playing with the devtools anyway, you'll probably learn this quickly and more intuitively. I propose axing that section, what do you think?
> A light cleanup edit

- _config.yml
- source/ember.md
Adding ember integration to docs per https://github.com/apollostack/apollo/issues/41
> Add documentation for Ember integration

- source/network.md
Fixes https://github.com/apollostack/apollo-client/issues/1126
> Remove outdated branching docs.

- source/meteor.md
Hey 👋
Docs update related to:
- New options to use (or not) a `BatchedInterface`, change from `options` to `opts` for `fetch` + link to the `fetch` docs: https://github.com/apollostack/meteor-integration/pull/62
- New option `cookieLoginToken` option to send with the queries when doing SSR: https://github.com/apollostack/meteor-integration/pull/57
- A note about `client.resetStore` in the `Meteor.logout` callback (https://github.com/apollostack/meteor-integration/issues/52#issuecomment-259593212)
Cheers,
*Note: I'm not an English-native. Please don't hesitate to tell me if I should change the wording or explain something differently* 👍
> Update Meteor docs related to recent activity on the meteor/apollo package

- source/meteor.md
@xavcz, here is the PR you asked for in https://github.com/apollographql/meteor-integration/issues/5#issuecomment-258599375
Let me know if it's ok like this!
> Add basic documentation about Blaze-Apollo

- source/meteor.md
Hey!
Related to the latest updates of `meteor/apollo` package, here is an update of the docs.
This PR mainly consists in:
- explaining that it's about extendable/replaceable pre-configuration, and giving the defaults config for each API functions,
- updating the SSR part with an example of grabbing the login token from the cookies thanks to a 3rd party package 
Also updated the code tour, as of the recent updates :octocat:
> Update meteor.md, related to latest package updates

- source/network.md
I'm not sure how detailed this should be or what extra notes should I add. People can already find usage example in this page. Should I add something else?
Related to #231
> Add some extra info about the req parameter of the applyMiddleware

- source/devtools.md
Fixing a typo in the docs for devtools.md
> Update devtools.md to fix a typo

- source/how-it-works.md
Also made docs more substantial for `dataIdFromObject` in general
> added docs for default dataIdFromObject selector

- source/meteor.md
As requested in https://github.com/apollographql/meteor-integration/issues/42#issuecomment-290410396
cc @xavcz
> Document `.graphql` file imports in Meteor

- source/meteor.md
👋  hey!
After speaking with @rdickert, we think that the most reliable and easiest way for people to get to consume GraphQL subscriptions in their Meteor app is... thanks to documentation! 📖 
So here are two ready-to-use snippets for client & server setup in a Meteor app, with words of warning about Redis/MQTT for production. These snippets are from the original attempt to include subs in `meteor/apollo`.
Note: I've experimented with Meteor + observables or hooking subscriptions on DDP but failed... for the moment ⚗️
> Documented code for subscriptions in Meteor

- source/index.md
> Just Angular

- source/network.md
Added WebSocket network interface using `subscriptions-transport-ws`.
Also, updated git submodule to latest to fix https://github.com/apollographql/core-docs/issues/277
> Updated subscriptions docs 

- source/meteor.md
:wave:
This PR on `meteor.html`:
- adds a Typings section with a link to https://github.com/KeithGillette/Apollo-GraphQL-Meteor-Integration-Typings 
- tweak some stuff in the subscription part per the comments on #274 
Btw, the hexo problem seems to be fixed thanks to #293 🎉
> Meteor - subscriptions update & typings section

- source/network.md
https://github.com/apollographql/graphql-tag/issues/54
> Printer is no longer in graphql-tag

- source/network.md
Added documentation for the batchMax option.
PR: https://github.com/apollographql/apollo-client/pull/1659
> Added batchMax to the Query batching explanation.

- source/apollo-client-api.md
Together with https://github.com/apollographql/apollo-client/pull/1932 it will make subscribe more discoverable.
> Add ApolloClient.subscribe
