source/apollo-client/core.md
source/apollo-client/react.md

It's going to be required as of the next release of `apollo-client` to use the `gql` template literal everywhere.
@jbaxleyiii @abhiaiyer91 thoughts? Anything else I should mention in the docs?

Add `gql` to docs

---

source/apollo-client/index.md
source/apollo-server/tools.md

After splitting the apolloServer and apolloClient based on the meteor-starter kit repo I ran into CORS errors which prevented the client from accessing the apollo-server. The remedy was to configure the express engine to use the npm cors. The docs have been updated to reflect proper setup.

CORS Support doc and config

---

source/apollo-server/tools.md

Documentation update for [Allows resolvers to be used with
mocks](https://github.com/apollostack/apollo-server/pull/9) (https://github.com/apollostack/apollo-server/pull/9)

apolloServer mocks no longer overwrite resolvers

---

source/apollo-client/core.md

This makes a recommendation to import the `gql` tag wherever it is used, and let's people know how to manually set it as a global as they wish. The `registerGqlTag()` function may be deprecated.

Recommend importing gql literal into each file

---

source/apollo-client/react.md

Added the ``` to the bottom of the page, github renders it fine without but the docs break.

Fixed react.md in apollo docs.

---

source/apollo-client/queries.md

correcting docs:
`refetch()`, `stopPolling()`, `startPolling()` are part of `queryObservable` not `subscription`

corrected object name where refetch(), stopPolling(), startPolling() are being called

---

source/apollo-server/graphiql.md
source/apollo-server/setup.md

Was pulling my hair out for half an hour because I was using koa 1.x but the middleware provided by apollo is for 2.x only.
[https://github.com/apollostack/apollo-server/issues/84](https://github.com/apollostack/apollo-server/issues/84)

mention koa 2 in server docs

---

source/graphql-tools/scalars.md

A light pass of grammar and typo fixes.
Also make sure to consistently use American "serialiZation"
spelling (consistent with the API name) and long lines for
paragraphs (as arbitrary linebreaks do show up in the HTML).

graphql-tools/scalars: copy editing

---

source/apollo-client/redux.md

When trying out this code I noticed `compose` does not get imported anywhere. This could be confusing since there is an npm package named `compose`. I know too little of `redux` to be certain whether this npm package is used internally, but when browsing through the `apollo-client` source, I noticed the `compose` function is imported via the `redux` package.

Add missing compose import

---

source/index.md

After some thinking I realised that by helping "getting off the ground", the [apollostack/apollo-starter-kit](https://github.com/apollostack/apollo-starter-kit) repository was aiming to teach people to start with GraphQL and Apollo (which was my case, thank you!) but it was not going further. There is a gap in between "learn this technology" and "this is how you should be using it". 
I couldn't find such thing in any of the other repos of `apollostack` as well, and trying to cover this gap I created the [perfect-graphql-starter](https://github.com/Quadric/perfect-graphql-starter/). I hope someone likes it!  😄 
Could we add a link to it in docs?

A new GraphQL server starter-kit

---

_config.yml
source/meteor.md
source/vue.md

@stubailo What do you think of adding integrations like this? Another option might be to have an 'Other' or 'External' sibling to 'Meteor' and simply list them in there.

Adds vue.js to integrations section

---

source/network.md

This PR adds documentation about chaining use() and useAfter() calls on a network interface. The corresponding PR which adds this feature is https://github.com/apollostack/apollo-client/pull/860
Remark : this is a new feature.

Network interface : document chaining use() and useAfter() calls

---

source/network.md

the `shouldBatch` option was removed in v0.5 in lieu of the `BatchedNetworkInterface` - reflecting that change in the example caption.

Updating "query batching" section to v0.5

---

source/meteor.md

This adds a section in Meteor integration about Accounts. It recommends the use of https://github.com/nicolaslopezj/meteor-apollo-accounts for GraphQL only authentication.

Add meteor accounts information

---

source/network.md

I had a little bit of trouble migrating from a previous version of Apollo Client where the `fetch` options weren't an explicit key in the `createNetworkInterface` function. I added some clarifying language in the `createBatchingNetworkInterface` part to make sure it was clear that one additional option was available (along with the other options from `createNetworkInterface`) and left an example in both parts to make it extremely clear.

Clarifying existence of `opts` option in createNetworkInterface

---

source/meteor.md

It looks like there was a typo in the docs Meteor's DPP I think should read Meteor's DDP.

Typo DPP to DDP

---

source/ember.md

I made an Ember addon for apollo-client: https://github.com/bgentry/ember-apollo-client
I wasn't sure what the right way to add this to the docs was since there are multiple Ember addons for apollo-client. I was going to put mine second since it was not the first one published, but ultimately I decided it made sense to put it first since it's a cleaner integration, is more fleshed out, and is more tested.
Up to you folks how you want to handle this :v:

Add ember-apollo-client to Ember integration page

---

source/meteor.md

Adds more details about creating a schema.js and a resolvers.js file when using the createApolloServer module. It helps at providing a better step by step example to run the Apollo package with Meteor.

Clarifies the Apollo Meteor docs

---

source/network.md

Noticed that while trying to implement custom network interface. `GraphQLRequest` documentation incorrectly specifies 2 fields:
- `query` field will actually contain AST, not query.
- There is no `debugName`, there is only `operationName`
[Same type definition in apollo-client](https://github.com/apollostack/apollo-client/blob/master/src/transport/networkInterface.ts#L25)

Correct GraphQLRequest signature

---

.gitmodules
_config.yml
circle.yml
package.json
source/apollo-client-api.md
source/data-control.md
source/read-and-write.md

This PR adds docs for the new read and write methods added in https://github.com/apollographql/apollo-client/pull/1310
There is some work that needs to be done to get the API documentation looking good. I’m almost done with that, I am just hitting a problem with `typedoc` rendering of generic return types where `readQuery<T>(options: DataProxyReadQueryOptions): T` and `readFragment<T>(options: DataProxyReadFragmentOptions): T | null` renders to:
If you have a fix for this, let me know. Otherwise, I’ll update this thread when I’ve found a solution.
cc @stubailo, @helfer

Imperative read and write docs

---

source/network.md

Following up on https://github.com/apollographql/apollo-client/pull/1285, this adds documentation about batch middlewares and batch afterwares.

Add documentation for batch wares

---

source/meteor.md

👋 
Here are minor adjustments on the Meteor-related docs: note about the default `dataIdFromObject` (yay!) & correct value of one of the pre-configured options on the network interface.

Meteor minor adjustments

---

package.json

Reverts apollographql/core-docs#278
Just remembered that hexo breaks code highlighting. Doh!

Revert "Update all dependencies 🌴"

---

source/meteor.md

It appears to me that `meteor.md` documentation references to `createMeteorNetworkInterface` should actually be `createNetworkInterface` to match function name in the source code.

Replace `createMeteorNetworkInterface` with `createNetworkInterface` in `meteor.md`

---

source/apollo-client-api.md

As discussed in [apollographql/apollo-client#1657 (comment)](https://github.com/apollographql/apollo-client/issues/1657#issuecomment-299536799)
Merge after apollographql/react-docs#221
CC: @helfer

Add docs for the exposure of 'dataIdFromObject' and 'dataId'

---

source/meteor.md

Reverts apollographql/core-docs#284
I think it was merged by mistake.

Revert "Replace `createMeteorNetworkInterface` with `createNetworkInterface` in `meteor.md`"

---

source/index.md

Link pointed to /angular, which returns a 403

Fixed angular link

---

source/network.md

Addresses https://github.com/apollographql/core-docs/issues/314
Adds clarification on the unit of time for `batchInterval` to the docs

Add unit of time for batchInterval in query batching description

---

source/meteor.md

There is wrong import statement in SSR section.
It uses `createMeteorNetworkInterface`, but `createNetworkInterface` is imported.

Fix createMeteorNetworkInterface in SSR section

---

source/read-and-write.md

Noticed this in the docs:
:point_up: Notice the extra `[]`.
So I updated to what I think is the correct formatting based on other links in the docs.

Fix link formatting

---

source/index.md

This repo is just a simple playground for GraphQL n00bs like me. It's only `client.js` and `server.js` both under 50 lines.
Having a minimalist sandbox like this helped me wrap my mind around Apollo, before I started adding all the ceremony that comes along with a UI and database.
Thanks!

adding a super simple client/server example

---

source/network.md

I noticed that the default for `queryDeduplication` has changed to true recently ([see source](https://github.com/apollographql/apollo-client/blob/25e38f5782128a07256e3e1878422403b1b6138c/src/ApolloClient.ts#L199)) but the docs were outdated.
I've also seen that [the `queryDeduplication` option of `QueryManager` defaults to false](https://github.com/apollographql/apollo-client/blob/13ecb9a280f763c02e384743eedff9acb02218b4/src/core/QueryManager.ts#L164), but is overridden by the default from `ApolloClient`. Is that class used independently of `ApolloClient`? If not, maybe it's a good idea to remove that default there.
---
On a different note: I was wondering if partial query deduplication could also be a thing? Consider the following query:
```
query Book($bookId: ID!) {
book(id: $bookId) …
```

Fix outdated queryDeduplication docs
